"""add status to price alerts"""

revision = '3c7bfeabf537'
down_revision = 'f3d287bebdea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_alerts', sa.Column('is_triggered', sa.Boolean(), nullable=False))
    op.add_column('price_alerts', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_alerts', 'status')
    op.drop_column('price_alerts', 'is_triggered')
    # ### end Alembic commands ###
