"""add ai and tracking fields"""

revision = '442061f44a12'
down_revision = '69e1aac629fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('stock_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_history_recorded_at'), 'stock_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_stock_history_sku_id'), 'stock_history', ['sku_id'], unique=False)
    op.add_column('product_skus', sa.Column('visual_hash', sa.String(length=128), nullable=True))
    op.add_column('product_skus', sa.Column('last_screenshot', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('ai_attributes', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('reviews', sa.Column('sentiment_label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'sentiment_label')
    op.drop_column('reviews', 'sentiment_score')
    op.drop_column('products', 'ai_attributes')
    op.drop_column('product_skus', 'last_screenshot')
    op.drop_column('product_skus', 'visual_hash')
    op.drop_index(op.f('ix_stock_history_sku_id'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_recorded_at'), table_name='stock_history')
    op.drop_table('stock_history')
    # ### end Alembic commands ###
