"""Add user table for production auth"""

revision = '48bd838e9d0e'
down_revision = '708dd01f7f26'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('home_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('price_alerts', sa.Column('notify_methods', sa.String(length=100), server_default='web', nullable=False))
    op.add_column('price_alerts', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('price_alerts', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('risk_scores', sa.Column('price_abnormal', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('risk_scores', sa.Column('rating_low', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'rating_low')
    op.drop_column('risk_scores', 'price_abnormal')
    op.drop_column('price_alerts', 'phone')
    op.drop_column('price_alerts', 'email')
    op.drop_column('price_alerts', 'notify_methods')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
