"""Add UserFollow model"""

revision = '4aff6160a642'
down_revision = '9b0e7292ca55'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_follows_product_id'), 'user_follows', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_follows_user_id'), 'user_follows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_follows_user_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_product_id'), table_name='user_follows')
    op.drop_table('user_follows')
    # ### end Alembic commands ###
