"""add platform health metrics table"""

revision = '69e1aac629fc'
down_revision = '4b0c5252af3a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('error_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_health_metrics_id'), 'platform_health_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_platform_health_metrics_platform'), 'platform_health_metrics', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_health_metrics_timestamp'), 'platform_health_metrics', ['timestamp'], unique=False)
    op.create_table('scraper_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_alerts_id'), 'scraper_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_alerts_platform'), 'scraper_alerts', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraper_alerts_platform'), table_name='scraper_alerts')
    op.drop_index(op.f('ix_scraper_alerts_id'), table_name='scraper_alerts')
    op.drop_table('scraper_alerts')
    op.drop_index(op.f('ix_platform_health_metrics_timestamp'), table_name='platform_health_metrics')
    op.drop_index(op.f('ix_platform_health_metrics_platform'), table_name='platform_health_metrics')
    op.drop_index(op.f('ix_platform_health_metrics_id'), table_name='platform_health_metrics')
    op.drop_table('platform_health_metrics')
    # ### end Alembic commands ###
