"""add current_interval to platform health"""

revision = '6bf4f4e70111'
down_revision = '442061f44a12'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_health_metrics', sa.Column('current_interval', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_health_metrics', 'current_interval')
    # ### end Alembic commands ###
