"""add triggered history columns to price alerts"""

revision = '708dd01f7f26'
down_revision = '16beff2aead1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_alerts', sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('price_alerts', sa.Column('triggered_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_alerts', 'triggered_price')
    op.drop_column('price_alerts', 'triggered_at')
    # ### end Alembic commands ###
