"""add_stock_status_to_sku"""

revision = '9b0e7292ca55'
down_revision = '48bd838e9d0e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_skus', sa.Column('stock_status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_skus', 'stock_status')
    # ### end Alembic commands ###
