"""add title and desc to coupon"""

revision = 'f3d287bebdea'
down_revision = '55ec85af44eb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('coupons', sa.Column('desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'desc')
    op.drop_column('coupons', 'title')
    # ### end Alembic commands ###
